name: 'PR Comment'
description: 'Comments to the PR'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: '.github/actions/pr-comment/dist/index.js'