name: PR comment
on: [pull_request]


jobs:
  pr_comment_job:
    runs-on: ubuntu-latest
    name: A job to comment to the PR
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Hello world action step
        id: hello
        uses: ./.github/actions/pr-comment